apiVersion: v1
data:
  node_general.yml: |
    - targets:
        - '10.101.11.236:19100'
        - '10.101.11.168:19100'
        - '10.101.11.188:19100'
        - '10.101.11.197:19100'
        - '10.101.11.163:19100'
        - '10.101.11.143:19100'
        - '10.101.11.149:19100'
        - '10.101.11.245:19100'
        - '10.101.11.130:19100'
        - '10.101.11.165:19100'
        - '10.101.11.224:19100'
        - '10.101.11.22:19100'
        - '10.101.11.241:19100'
        - '10.101.11.10:19100'
        - '10.101.11.99:19100'
        - '10.101.11.65:19100'
        - '10.101.11.147:19100'
        - '10.101.11.174:19100'
        - '10.101.11.132:19100'
        - '10.101.11.31:19100'
        - '10.101.11.108:19100'
        - '10.101.11.104:19100'
        - '10.101.11.100:19100'
        - '10.101.11.91:19100'
        - '10.101.11.84:19100'
        - '10.101.11.77:19100'
        - '10.101.11.71:19100'
        - '10.101.11.109:19100'
        - '10.101.11.34:19100'
        - '10.101.11.15:19100'
        - '10.101.11.92:19100'
        - '10.101.11.88:19100'
        - '10.101.11.90:19100'
        - '10.101.11.87:19100'
        - '10.101.11.80:19100'
        - '10.101.11.70:19100'
        - '10.101.11.74:19100'
        - '10.101.11.76:19100'
        - '10.101.11.36:19100'
        - '10.101.11.209:19100'
        - '10.101.11.30:19100'
        - '10.101.11.123:19100'
        - '10.101.11.23:19100'
        - '10.101.11.8:19100'
      labels:
        author: Jesse
        env: lab
  node_ci.yml: |
    - targets:
        - 10.101.9.172:19100
        - 10.101.9.202:19100
        - 10.101.9.170:19100
        - 10.101.9.173:19100
        - 10.101.9.171:19100
        - 10.101.9.175:19100
        - 10.101.9.219:19100
        - 10.101.9.215:19100
        - 10.101.9.209:19100
        - 10.101.9.206:19100
        - 10.101.9.7:19100
        - 10.101.9.117:19100
        - 10.101.9.214:19100
        - 10.101.9.228:19100
        - 10.101.9.143:19100
        - 10.101.9.252:19100
        - 10.101.9.196:19100
        - 10.101.9.218:19100
        - 10.101.9.217:19100
      labels:
        author: Jesse
        env: lab
kind: ConfigMap
metadata:
  labels:
    app: prometheus-metadata-hosts
  name: prometheus-metadata-hosts
  namespace: kube-server
